// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nixprotocol/privacy/v1/genesis.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the privacy module's genesis state.
type GenesisState struct {
	Params           *Params                 `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Trees            []*TreeState            `protobuf:"bytes,2,rep,name=trees,proto3" json:"trees,omitempty"`
	ActiveTreeId     uint64                  `protobuf:"varint,3,opt,name=active_tree_id,json=activeTreeId,proto3" json:"active_tree_id,omitempty"`
	TreeCount        uint64                  `protobuf:"varint,4,opt,name=tree_count,json=treeCount,proto3" json:"tree_count,omitempty"`
	RegCommitments   [][]byte                `protobuf:"bytes,5,rep,name=reg_commitments,json=regCommitments,proto3" json:"reg_commitments,omitempty"`
	RegFrontier      [][]byte                `protobuf:"bytes,6,rep,name=reg_frontier,json=regFrontier,proto3" json:"reg_frontier,omitempty"`
	RegNextIndex     uint64                  `protobuf:"varint,7,opt,name=reg_next_index,json=regNextIndex,proto3" json:"reg_next_index,omitempty"`
	RegMerkleRoot    []byte                  `protobuf:"bytes,8,opt,name=reg_merkle_root,json=regMerkleRoot,proto3" json:"reg_merkle_root,omitempty"`
	Nullifiers       [][]byte                `protobuf:"bytes,9,rep,name=nullifiers,proto3" json:"nullifiers,omitempty"`
	AuditorData      []*AuditorDataEntry     `protobuf:"bytes,10,rep,name=auditor_data,json=auditorData,proto3" json:"auditor_data,omitempty"`
	CommitmentsUsed  [][]byte                `protobuf:"bytes,11,rep,name=commitments_used,json=commitmentsUsed,proto3" json:"commitments_used,omitempty"`
	VerificationKeys []*VerificationKeyEntry `protobuf:"bytes,12,rep,name=verification_keys,json=verificationKeys,proto3" json:"verification_keys,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f179bed0a4ec446, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *GenesisState) GetTrees() []*TreeState {
	if m != nil {
		return m.Trees
	}
	return nil
}

func (m *GenesisState) GetActiveTreeId() uint64 {
	if m != nil {
		return m.ActiveTreeId
	}
	return 0
}

func (m *GenesisState) GetTreeCount() uint64 {
	if m != nil {
		return m.TreeCount
	}
	return 0
}

func (m *GenesisState) GetRegCommitments() [][]byte {
	if m != nil {
		return m.RegCommitments
	}
	return nil
}

func (m *GenesisState) GetRegFrontier() [][]byte {
	if m != nil {
		return m.RegFrontier
	}
	return nil
}

func (m *GenesisState) GetRegNextIndex() uint64 {
	if m != nil {
		return m.RegNextIndex
	}
	return 0
}

func (m *GenesisState) GetRegMerkleRoot() []byte {
	if m != nil {
		return m.RegMerkleRoot
	}
	return nil
}

func (m *GenesisState) GetNullifiers() [][]byte {
	if m != nil {
		return m.Nullifiers
	}
	return nil
}

func (m *GenesisState) GetAuditorData() []*AuditorDataEntry {
	if m != nil {
		return m.AuditorData
	}
	return nil
}

func (m *GenesisState) GetCommitmentsUsed() [][]byte {
	if m != nil {
		return m.CommitmentsUsed
	}
	return nil
}

func (m *GenesisState) GetVerificationKeys() []*VerificationKeyEntry {
	if m != nil {
		return m.VerificationKeys
	}
	return nil
}

// TreeState captures the full state of a single Merkle tree.
type TreeState struct {
	TreeId      uint64   `protobuf:"varint,1,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	Commitments [][]byte `protobuf:"bytes,2,rep,name=commitments,proto3" json:"commitments,omitempty"`
	Frontier    [][]byte `protobuf:"bytes,3,rep,name=frontier,proto3" json:"frontier,omitempty"`
	NextIndex   uint64   `protobuf:"varint,4,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`
	MerkleRoot  []byte   `protobuf:"bytes,5,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	RootHistory [][]byte `protobuf:"bytes,6,rep,name=root_history,json=rootHistory,proto3" json:"root_history,omitempty"`
}

func (m *TreeState) Reset()         { *m = TreeState{} }
func (m *TreeState) String() string { return proto.CompactTextString(m) }
func (*TreeState) ProtoMessage()    {}
func (*TreeState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f179bed0a4ec446, []int{1}
}
func (m *TreeState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TreeState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TreeState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TreeState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreeState.Merge(m, src)
}
func (m *TreeState) XXX_Size() int {
	return m.Size()
}
func (m *TreeState) XXX_DiscardUnknown() {
	xxx_messageInfo_TreeState.DiscardUnknown(m)
}

var xxx_messageInfo_TreeState proto.InternalMessageInfo

func (m *TreeState) GetTreeId() uint64 {
	if m != nil {
		return m.TreeId
	}
	return 0
}

func (m *TreeState) GetCommitments() [][]byte {
	if m != nil {
		return m.Commitments
	}
	return nil
}

func (m *TreeState) GetFrontier() [][]byte {
	if m != nil {
		return m.Frontier
	}
	return nil
}

func (m *TreeState) GetNextIndex() uint64 {
	if m != nil {
		return m.NextIndex
	}
	return 0
}

func (m *TreeState) GetMerkleRoot() []byte {
	if m != nil {
		return m.MerkleRoot
	}
	return nil
}

func (m *TreeState) GetRootHistory() [][]byte {
	if m != nil {
		return m.RootHistory
	}
	return nil
}

type AuditorDataEntry struct {
	TxHash []byte `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *AuditorDataEntry) Reset()         { *m = AuditorDataEntry{} }
func (m *AuditorDataEntry) String() string { return proto.CompactTextString(m) }
func (*AuditorDataEntry) ProtoMessage()    {}
func (*AuditorDataEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f179bed0a4ec446, []int{2}
}
func (m *AuditorDataEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AuditorDataEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AuditorDataEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AuditorDataEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuditorDataEntry.Merge(m, src)
}
func (m *AuditorDataEntry) XXX_Size() int {
	return m.Size()
}
func (m *AuditorDataEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_AuditorDataEntry.DiscardUnknown(m)
}

var xxx_messageInfo_AuditorDataEntry proto.InternalMessageInfo

func (m *AuditorDataEntry) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *AuditorDataEntry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type VerificationKeyEntry struct {
	CircuitName string `protobuf:"bytes,1,opt,name=circuit_name,json=circuitName,proto3" json:"circuit_name,omitempty"`
	VkData      []byte `protobuf:"bytes,2,opt,name=vk_data,json=vkData,proto3" json:"vk_data,omitempty"`
}

func (m *VerificationKeyEntry) Reset()         { *m = VerificationKeyEntry{} }
func (m *VerificationKeyEntry) String() string { return proto.CompactTextString(m) }
func (*VerificationKeyEntry) ProtoMessage()    {}
func (*VerificationKeyEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f179bed0a4ec446, []int{3}
}
func (m *VerificationKeyEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerificationKeyEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerificationKeyEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerificationKeyEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationKeyEntry.Merge(m, src)
}
func (m *VerificationKeyEntry) XXX_Size() int {
	return m.Size()
}
func (m *VerificationKeyEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationKeyEntry.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationKeyEntry proto.InternalMessageInfo

func (m *VerificationKeyEntry) GetCircuitName() string {
	if m != nil {
		return m.CircuitName
	}
	return ""
}

func (m *VerificationKeyEntry) GetVkData() []byte {
	if m != nil {
		return m.VkData
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "nixprotocol.privacy.v1.GenesisState")
	proto.RegisterType((*TreeState)(nil), "nixprotocol.privacy.v1.TreeState")
	proto.RegisterType((*AuditorDataEntry)(nil), "nixprotocol.privacy.v1.AuditorDataEntry")
	proto.RegisterType((*VerificationKeyEntry)(nil), "nixprotocol.privacy.v1.VerificationKeyEntry")
}

func init() {
	proto.RegisterFile("nixprotocol/privacy/v1/genesis.proto", fileDescriptor_8f179bed0a4ec446)
}

var fileDescriptor_8f179bed0a4ec446 = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0xc7, 0xeb, 0x26, 0x4d, 0x9b, 0xb5, 0x9f, 0xb6, 0xcf, 0x0a, 0x81, 0x55, 0x09, 0x93, 0x46,
	0x15, 0x04, 0x41, 0x13, 0xb5, 0x48, 0x70, 0x44, 0x50, 0x0a, 0xad, 0x2a, 0x2a, 0x64, 0x5e, 0x24,
	0xb8, 0x58, 0x5b, 0x7b, 0xea, 0xac, 0x12, 0xef, 0x46, 0xbb, 0x13, 0xcb, 0xf9, 0x16, 0x7c, 0x29,
	0x24, 0x8e, 0xe5, 0xc6, 0x11, 0xb5, 0x5f, 0x04, 0xed, 0xda, 0xa4, 0x06, 0x35, 0x37, 0xfb, 0x37,
	0xff, 0x79, 0xf1, 0xfc, 0xc7, 0x64, 0x47, 0xf0, 0x62, 0xa2, 0x24, 0xca, 0x58, 0x8e, 0x07, 0x13,
	0xc5, 0x73, 0x16, 0xcf, 0x06, 0xf9, 0xde, 0x20, 0x05, 0x01, 0x9a, 0xeb, 0xbe, 0x8d, 0xd1, 0xdb,
	0x35, 0x55, 0xbf, 0x52, 0xf5, 0xf3, 0xbd, 0xad, 0xee, 0x82, 0x6c, 0x9c, 0x4d, 0xa0, 0xca, 0xed,
	0xfe, 0x68, 0x12, 0xef, 0x4d, 0x59, 0xed, 0x3d, 0x32, 0x04, 0xfa, 0x94, 0xb4, 0x26, 0x4c, 0xb1,
	0x4c, 0xfb, 0x4e, 0xc7, 0xe9, 0xb9, 0xfb, 0x41, 0xff, 0xe6, 0xea, 0xfd, 0x77, 0x56, 0x15, 0x56,
	0x6a, 0xfa, 0x8c, 0xac, 0xa0, 0x02, 0xd0, 0xfe, 0x72, 0xa7, 0xd1, 0x73, 0xf7, 0xb7, 0x17, 0xa5,
	0x7d, 0x50, 0x00, 0xb6, 0x53, 0x58, 0xea, 0xe9, 0x0e, 0x59, 0x67, 0x31, 0xf2, 0x1c, 0x22, 0xf3,
	0x1e, 0xf1, 0xc4, 0x6f, 0x74, 0x9c, 0x5e, 0x33, 0xf4, 0x4a, 0x6a, 0xf4, 0xc7, 0x09, 0xbd, 0x4b,
	0x88, 0x0d, 0xc7, 0x72, 0x2a, 0xd0, 0x6f, 0x5a, 0x45, 0xdb, 0x90, 0x03, 0x03, 0xe8, 0x03, 0xb2,
	0xa1, 0x20, 0x8d, 0x62, 0x99, 0x65, 0x1c, 0x33, 0x10, 0xa8, 0xfd, 0x95, 0x4e, 0xa3, 0xe7, 0x85,
	0xeb, 0x0a, 0xd2, 0x83, 0x6b, 0x4a, 0xb7, 0x89, 0x67, 0x84, 0xe7, 0x4a, 0x0a, 0xe4, 0xa0, 0xfc,
	0x96, 0x55, 0xb9, 0x0a, 0xd2, 0xd7, 0x15, 0x32, 0x03, 0x19, 0x89, 0x80, 0x02, 0x23, 0x2e, 0x12,
	0x28, 0xfc, 0xd5, 0x72, 0x20, 0x05, 0xe9, 0x29, 0x14, 0x78, 0x6c, 0x18, 0xbd, 0x5f, 0x76, 0xcc,
	0x40, 0x8d, 0xc6, 0x10, 0x29, 0x29, 0xd1, 0x5f, 0xeb, 0x38, 0x3d, 0x2f, 0xfc, 0x4f, 0x41, 0xfa,
	0xd6, 0xd2, 0x50, 0x4a, 0xa4, 0x01, 0x21, 0x62, 0x3a, 0x1e, 0xf3, 0x73, 0x0e, 0x4a, 0xfb, 0x6d,
	0xdb, 0xae, 0x46, 0xe8, 0x09, 0xf1, 0xd8, 0x34, 0xe1, 0x28, 0x55, 0x94, 0x30, 0x64, 0x3e, 0xb1,
	0xeb, 0xeb, 0x2d, 0x5a, 0xdf, 0x8b, 0x52, 0xfb, 0x8a, 0x21, 0x3b, 0x14, 0xa8, 0x66, 0xa1, 0xcb,
	0xae, 0x09, 0x7d, 0x48, 0x36, 0x6b, 0x2b, 0x88, 0xa6, 0x1a, 0x12, 0xdf, 0xb5, 0x2d, 0x37, 0x6a,
	0xfc, 0xa3, 0x86, 0x84, 0x7e, 0x26, 0xff, 0xe7, 0xa0, 0xf8, 0x39, 0x8f, 0x19, 0x72, 0x29, 0xa2,
	0x11, 0xcc, 0xb4, 0xef, 0xd9, 0xe6, 0x8f, 0x17, 0x35, 0xff, 0x54, 0x4b, 0x38, 0x81, 0x59, 0x39,
	0xc0, 0x66, 0xfe, 0x37, 0xd5, 0xdd, 0x6f, 0x0e, 0x69, 0xcf, 0x6d, 0xa6, 0x77, 0xc8, 0xea, 0x1f,
	0x63, 0x1d, 0xbb, 0xc7, 0x16, 0x96, 0x96, 0x76, 0x88, 0x5b, 0xf7, 0x6b, 0xb9, 0x74, 0xa2, 0x86,
	0xe8, 0x16, 0x59, 0x9b, 0x1b, 0xd5, 0xb0, 0xe1, 0xf9, 0xbb, 0x39, 0x88, 0x9a, 0x43, 0xd5, 0x41,
	0x88, 0xb9, 0x3d, 0xf7, 0x88, 0x5b, 0xb7, 0x66, 0xc5, 0x5a, 0x43, 0xb2, 0x6b, 0x5f, 0xcc, 0x21,
	0x48, 0x89, 0xd1, 0x90, 0x6b, 0x94, 0x6a, 0x36, 0x3f, 0x04, 0x29, 0xf1, 0xa8, 0x44, 0xdd, 0xe7,
	0x64, 0xf3, 0xdf, 0x75, 0xdb, 0xaf, 0x29, 0xa2, 0x21, 0xd3, 0x43, 0xfb, 0x35, 0x5e, 0xd8, 0xc2,
	0xe2, 0x88, 0xe9, 0x21, 0xa5, 0xa4, 0x69, 0xfd, 0x5b, 0xb6, 0xd4, 0x3e, 0x77, 0x43, 0x72, 0xeb,
	0xa6, 0x95, 0x99, 0xde, 0x31, 0x57, 0xf1, 0x94, 0x63, 0x24, 0x58, 0x06, 0xb6, 0x52, 0x3b, 0x74,
	0x2b, 0x76, 0xca, 0x32, 0xbb, 0xb5, 0x7c, 0x14, 0xd5, 0x2a, 0xb6, 0xf2, 0x91, 0x99, 0xe2, 0xe5,
	0xe1, 0xf7, 0xcb, 0xc0, 0xb9, 0xb8, 0x0c, 0x9c, 0x5f, 0x97, 0x81, 0xf3, 0xf5, 0x2a, 0x58, 0xba,
	0xb8, 0x0a, 0x96, 0x7e, 0x5e, 0x05, 0x4b, 0x5f, 0x1e, 0xa5, 0x1c, 0x87, 0xd3, 0xb3, 0x7e, 0x2c,
	0xb3, 0x41, 0xfd, 0xcf, 0x17, 0xbc, 0xd8, 0x8d, 0xa5, 0xce, 0xa4, 0xde, 0xd5, 0xc9, 0xa8, 0xfc,
	0xfb, 0xcf, 0x5a, 0x36, 0xfc, 0xe4, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1f, 0x54, 0x4f, 0x52,
	0x62, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VerificationKeys) > 0 {
		for iNdEx := len(m.VerificationKeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VerificationKeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.CommitmentsUsed) > 0 {
		for iNdEx := len(m.CommitmentsUsed) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CommitmentsUsed[iNdEx])
			copy(dAtA[i:], m.CommitmentsUsed[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.CommitmentsUsed[iNdEx])))
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.AuditorData) > 0 {
		for iNdEx := len(m.AuditorData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AuditorData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.Nullifiers) > 0 {
		for iNdEx := len(m.Nullifiers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Nullifiers[iNdEx])
			copy(dAtA[i:], m.Nullifiers[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.Nullifiers[iNdEx])))
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.RegMerkleRoot) > 0 {
		i -= len(m.RegMerkleRoot)
		copy(dAtA[i:], m.RegMerkleRoot)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.RegMerkleRoot)))
		i--
		dAtA[i] = 0x42
	}
	if m.RegNextIndex != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.RegNextIndex))
		i--
		dAtA[i] = 0x38
	}
	if len(m.RegFrontier) > 0 {
		for iNdEx := len(m.RegFrontier) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RegFrontier[iNdEx])
			copy(dAtA[i:], m.RegFrontier[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.RegFrontier[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.RegCommitments) > 0 {
		for iNdEx := len(m.RegCommitments) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RegCommitments[iNdEx])
			copy(dAtA[i:], m.RegCommitments[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.RegCommitments[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.TreeCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TreeCount))
		i--
		dAtA[i] = 0x20
	}
	if m.ActiveTreeId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ActiveTreeId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Trees) > 0 {
		for iNdEx := len(m.Trees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Trees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TreeState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TreeState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TreeState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RootHistory) > 0 {
		for iNdEx := len(m.RootHistory) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RootHistory[iNdEx])
			copy(dAtA[i:], m.RootHistory[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.RootHistory[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.MerkleRoot) > 0 {
		i -= len(m.MerkleRoot)
		copy(dAtA[i:], m.MerkleRoot)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.MerkleRoot)))
		i--
		dAtA[i] = 0x2a
	}
	if m.NextIndex != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NextIndex))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Frontier) > 0 {
		for iNdEx := len(m.Frontier) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Frontier[iNdEx])
			copy(dAtA[i:], m.Frontier[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.Frontier[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Commitments) > 0 {
		for iNdEx := len(m.Commitments) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Commitments[iNdEx])
			copy(dAtA[i:], m.Commitments[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.Commitments[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.TreeId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TreeId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AuditorDataEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AuditorDataEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AuditorDataEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VerificationKeyEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerificationKeyEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VerificationKeyEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VkData) > 0 {
		i -= len(m.VkData)
		copy(dAtA[i:], m.VkData)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.VkData)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.CircuitName) > 0 {
		i -= len(m.CircuitName)
		copy(dAtA[i:], m.CircuitName)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.CircuitName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.Trees) > 0 {
		for _, e := range m.Trees {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ActiveTreeId != 0 {
		n += 1 + sovGenesis(uint64(m.ActiveTreeId))
	}
	if m.TreeCount != 0 {
		n += 1 + sovGenesis(uint64(m.TreeCount))
	}
	if len(m.RegCommitments) > 0 {
		for _, b := range m.RegCommitments {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RegFrontier) > 0 {
		for _, b := range m.RegFrontier {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.RegNextIndex != 0 {
		n += 1 + sovGenesis(uint64(m.RegNextIndex))
	}
	l = len(m.RegMerkleRoot)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.Nullifiers) > 0 {
		for _, b := range m.Nullifiers {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AuditorData) > 0 {
		for _, e := range m.AuditorData {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CommitmentsUsed) > 0 {
		for _, b := range m.CommitmentsUsed {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.VerificationKeys) > 0 {
		for _, e := range m.VerificationKeys {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *TreeState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TreeId != 0 {
		n += 1 + sovGenesis(uint64(m.TreeId))
	}
	if len(m.Commitments) > 0 {
		for _, b := range m.Commitments {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Frontier) > 0 {
		for _, b := range m.Frontier {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NextIndex != 0 {
		n += 1 + sovGenesis(uint64(m.NextIndex))
	}
	l = len(m.MerkleRoot)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.RootHistory) > 0 {
		for _, b := range m.RootHistory {
			l = len(b)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *AuditorDataEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *VerificationKeyEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CircuitName)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.VkData)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Trees = append(m.Trees, &TreeState{})
			if err := m.Trees[len(m.Trees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveTreeId", wireType)
			}
			m.ActiveTreeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveTreeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreeCount", wireType)
			}
			m.TreeCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TreeCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegCommitments", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegCommitments = append(m.RegCommitments, make([]byte, postIndex-iNdEx))
			copy(m.RegCommitments[len(m.RegCommitments)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegFrontier", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegFrontier = append(m.RegFrontier, make([]byte, postIndex-iNdEx))
			copy(m.RegFrontier[len(m.RegFrontier)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegNextIndex", wireType)
			}
			m.RegNextIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegNextIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegMerkleRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegMerkleRoot = append(m.RegMerkleRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.RegMerkleRoot == nil {
				m.RegMerkleRoot = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifiers", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifiers = append(m.Nullifiers, make([]byte, postIndex-iNdEx))
			copy(m.Nullifiers[len(m.Nullifiers)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditorData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditorData = append(m.AuditorData, &AuditorDataEntry{})
			if err := m.AuditorData[len(m.AuditorData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentsUsed", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitmentsUsed = append(m.CommitmentsUsed, make([]byte, postIndex-iNdEx))
			copy(m.CommitmentsUsed[len(m.CommitmentsUsed)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationKeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VerificationKeys = append(m.VerificationKeys, &VerificationKeyEntry{})
			if err := m.VerificationKeys[len(m.VerificationKeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TreeState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TreeState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TreeState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreeId", wireType)
			}
			m.TreeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TreeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Commitments", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Commitments = append(m.Commitments, make([]byte, postIndex-iNdEx))
			copy(m.Commitments[len(m.Commitments)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Frontier", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Frontier = append(m.Frontier, make([]byte, postIndex-iNdEx))
			copy(m.Frontier[len(m.Frontier)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextIndex", wireType)
			}
			m.NextIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerkleRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerkleRoot = append(m.MerkleRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.MerkleRoot == nil {
				m.MerkleRoot = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootHistory", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootHistory = append(m.RootHistory, make([]byte, postIndex-iNdEx))
			copy(m.RootHistory[len(m.RootHistory)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AuditorDataEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AuditorDataEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AuditorDataEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = append(m.TxHash[:0], dAtA[iNdEx:postIndex]...)
			if m.TxHash == nil {
				m.TxHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerificationKeyEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerificationKeyEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerificationKeyEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CircuitName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CircuitName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VkData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VkData = append(m.VkData[:0], dAtA[iNdEx:postIndex]...)
			if m.VkData == nil {
				m.VkData = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
