// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nixprotocol/privacy/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryRootRequest struct {
}

func (m *QueryRootRequest) Reset()         { *m = QueryRootRequest{} }
func (m *QueryRootRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRootRequest) ProtoMessage()    {}
func (*QueryRootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{0}
}
func (m *QueryRootRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRootRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRootRequest.Merge(m, src)
}
func (m *QueryRootRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRootRequest proto.InternalMessageInfo

type QueryRootResponse struct {
	Root []byte `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
}

func (m *QueryRootResponse) Reset()         { *m = QueryRootResponse{} }
func (m *QueryRootResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRootResponse) ProtoMessage()    {}
func (*QueryRootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{1}
}
func (m *QueryRootResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRootResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRootResponse.Merge(m, src)
}
func (m *QueryRootResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRootResponse proto.InternalMessageInfo

func (m *QueryRootResponse) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

type QueryNullifierStatusRequest struct {
	Nullifier []byte `protobuf:"bytes,1,opt,name=nullifier,proto3" json:"nullifier,omitempty"`
}

func (m *QueryNullifierStatusRequest) Reset()         { *m = QueryNullifierStatusRequest{} }
func (m *QueryNullifierStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryNullifierStatusRequest) ProtoMessage()    {}
func (*QueryNullifierStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{2}
}
func (m *QueryNullifierStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNullifierStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNullifierStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNullifierStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNullifierStatusRequest.Merge(m, src)
}
func (m *QueryNullifierStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryNullifierStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNullifierStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNullifierStatusRequest proto.InternalMessageInfo

func (m *QueryNullifierStatusRequest) GetNullifier() []byte {
	if m != nil {
		return m.Nullifier
	}
	return nil
}

type QueryNullifierStatusResponse struct {
	Spent bool `protobuf:"varint,1,opt,name=spent,proto3" json:"spent,omitempty"`
}

func (m *QueryNullifierStatusResponse) Reset()         { *m = QueryNullifierStatusResponse{} }
func (m *QueryNullifierStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryNullifierStatusResponse) ProtoMessage()    {}
func (*QueryNullifierStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{3}
}
func (m *QueryNullifierStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryNullifierStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryNullifierStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryNullifierStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNullifierStatusResponse.Merge(m, src)
}
func (m *QueryNullifierStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryNullifierStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNullifierStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNullifierStatusResponse proto.InternalMessageInfo

func (m *QueryNullifierStatusResponse) GetSpent() bool {
	if m != nil {
		return m.Spent
	}
	return false
}

type QueryTreeInfoRequest struct {
}

func (m *QueryTreeInfoRequest) Reset()         { *m = QueryTreeInfoRequest{} }
func (m *QueryTreeInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTreeInfoRequest) ProtoMessage()    {}
func (*QueryTreeInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{4}
}
func (m *QueryTreeInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTreeInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTreeInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTreeInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTreeInfoRequest.Merge(m, src)
}
func (m *QueryTreeInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTreeInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTreeInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTreeInfoRequest proto.InternalMessageInfo

type QueryTreeInfoResponse struct {
	NextIndex    uint64 `protobuf:"varint,1,opt,name=next_index,json=nextIndex,proto3" json:"next_index,omitempty"`
	Root         []byte `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`
	Depth        uint32 `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	ActiveTreeId uint64 `protobuf:"varint,4,opt,name=active_tree_id,json=activeTreeId,proto3" json:"active_tree_id,omitempty"`
	TreeCount    uint64 `protobuf:"varint,5,opt,name=tree_count,json=treeCount,proto3" json:"tree_count,omitempty"`
}

func (m *QueryTreeInfoResponse) Reset()         { *m = QueryTreeInfoResponse{} }
func (m *QueryTreeInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTreeInfoResponse) ProtoMessage()    {}
func (*QueryTreeInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{5}
}
func (m *QueryTreeInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTreeInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTreeInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTreeInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTreeInfoResponse.Merge(m, src)
}
func (m *QueryTreeInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTreeInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTreeInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTreeInfoResponse proto.InternalMessageInfo

func (m *QueryTreeInfoResponse) GetNextIndex() uint64 {
	if m != nil {
		return m.NextIndex
	}
	return 0
}

func (m *QueryTreeInfoResponse) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *QueryTreeInfoResponse) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *QueryTreeInfoResponse) GetActiveTreeId() uint64 {
	if m != nil {
		return m.ActiveTreeId
	}
	return 0
}

func (m *QueryTreeInfoResponse) GetTreeCount() uint64 {
	if m != nil {
		return m.TreeCount
	}
	return 0
}

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{6}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{7}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

type QueryRegistrationRootRequest struct {
}

func (m *QueryRegistrationRootRequest) Reset()         { *m = QueryRegistrationRootRequest{} }
func (m *QueryRegistrationRootRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRegistrationRootRequest) ProtoMessage()    {}
func (*QueryRegistrationRootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{8}
}
func (m *QueryRegistrationRootRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistrationRootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistrationRootRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistrationRootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistrationRootRequest.Merge(m, src)
}
func (m *QueryRegistrationRootRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistrationRootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistrationRootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistrationRootRequest proto.InternalMessageInfo

type QueryRegistrationRootResponse struct {
	Root []byte `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
}

func (m *QueryRegistrationRootResponse) Reset()         { *m = QueryRegistrationRootResponse{} }
func (m *QueryRegistrationRootResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRegistrationRootResponse) ProtoMessage()    {}
func (*QueryRegistrationRootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{9}
}
func (m *QueryRegistrationRootResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRegistrationRootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRegistrationRootResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRegistrationRootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRegistrationRootResponse.Merge(m, src)
}
func (m *QueryRegistrationRootResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRegistrationRootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRegistrationRootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRegistrationRootResponse proto.InternalMessageInfo

func (m *QueryRegistrationRootResponse) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

type QueryAuditorKeyRequest struct {
}

func (m *QueryAuditorKeyRequest) Reset()         { *m = QueryAuditorKeyRequest{} }
func (m *QueryAuditorKeyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAuditorKeyRequest) ProtoMessage()    {}
func (*QueryAuditorKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{10}
}
func (m *QueryAuditorKeyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuditorKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuditorKeyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuditorKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditorKeyRequest.Merge(m, src)
}
func (m *QueryAuditorKeyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuditorKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditorKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditorKeyRequest proto.InternalMessageInfo

type QueryAuditorKeyResponse struct {
	AuditorPubKey []byte `protobuf:"bytes,1,opt,name=auditor_pub_key,json=auditorPubKey,proto3" json:"auditor_pub_key,omitempty"`
}

func (m *QueryAuditorKeyResponse) Reset()         { *m = QueryAuditorKeyResponse{} }
func (m *QueryAuditorKeyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAuditorKeyResponse) ProtoMessage()    {}
func (*QueryAuditorKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{11}
}
func (m *QueryAuditorKeyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuditorKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuditorKeyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuditorKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuditorKeyResponse.Merge(m, src)
}
func (m *QueryAuditorKeyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuditorKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuditorKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuditorKeyResponse proto.InternalMessageInfo

func (m *QueryAuditorKeyResponse) GetAuditorPubKey() []byte {
	if m != nil {
		return m.AuditorPubKey
	}
	return nil
}

type QuerySupportedDenomsRequest struct {
}

func (m *QuerySupportedDenomsRequest) Reset()         { *m = QuerySupportedDenomsRequest{} }
func (m *QuerySupportedDenomsRequest) String() string { return proto.CompactTextString(m) }
func (*QuerySupportedDenomsRequest) ProtoMessage()    {}
func (*QuerySupportedDenomsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{12}
}
func (m *QuerySupportedDenomsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySupportedDenomsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySupportedDenomsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySupportedDenomsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySupportedDenomsRequest.Merge(m, src)
}
func (m *QuerySupportedDenomsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QuerySupportedDenomsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySupportedDenomsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySupportedDenomsRequest proto.InternalMessageInfo

type QuerySupportedDenomsResponse struct {
	Denoms []string `protobuf:"bytes,1,rep,name=denoms,proto3" json:"denoms,omitempty"`
}

func (m *QuerySupportedDenomsResponse) Reset()         { *m = QuerySupportedDenomsResponse{} }
func (m *QuerySupportedDenomsResponse) String() string { return proto.CompactTextString(m) }
func (*QuerySupportedDenomsResponse) ProtoMessage()    {}
func (*QuerySupportedDenomsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb4378f5df4cc1d, []int{13}
}
func (m *QuerySupportedDenomsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QuerySupportedDenomsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QuerySupportedDenomsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QuerySupportedDenomsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuerySupportedDenomsResponse.Merge(m, src)
}
func (m *QuerySupportedDenomsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QuerySupportedDenomsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuerySupportedDenomsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuerySupportedDenomsResponse proto.InternalMessageInfo

func (m *QuerySupportedDenomsResponse) GetDenoms() []string {
	if m != nil {
		return m.Denoms
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryRootRequest)(nil), "nixprotocol.privacy.v1.QueryRootRequest")
	proto.RegisterType((*QueryRootResponse)(nil), "nixprotocol.privacy.v1.QueryRootResponse")
	proto.RegisterType((*QueryNullifierStatusRequest)(nil), "nixprotocol.privacy.v1.QueryNullifierStatusRequest")
	proto.RegisterType((*QueryNullifierStatusResponse)(nil), "nixprotocol.privacy.v1.QueryNullifierStatusResponse")
	proto.RegisterType((*QueryTreeInfoRequest)(nil), "nixprotocol.privacy.v1.QueryTreeInfoRequest")
	proto.RegisterType((*QueryTreeInfoResponse)(nil), "nixprotocol.privacy.v1.QueryTreeInfoResponse")
	proto.RegisterType((*QueryParamsRequest)(nil), "nixprotocol.privacy.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "nixprotocol.privacy.v1.QueryParamsResponse")
	proto.RegisterType((*QueryRegistrationRootRequest)(nil), "nixprotocol.privacy.v1.QueryRegistrationRootRequest")
	proto.RegisterType((*QueryRegistrationRootResponse)(nil), "nixprotocol.privacy.v1.QueryRegistrationRootResponse")
	proto.RegisterType((*QueryAuditorKeyRequest)(nil), "nixprotocol.privacy.v1.QueryAuditorKeyRequest")
	proto.RegisterType((*QueryAuditorKeyResponse)(nil), "nixprotocol.privacy.v1.QueryAuditorKeyResponse")
	proto.RegisterType((*QuerySupportedDenomsRequest)(nil), "nixprotocol.privacy.v1.QuerySupportedDenomsRequest")
	proto.RegisterType((*QuerySupportedDenomsResponse)(nil), "nixprotocol.privacy.v1.QuerySupportedDenomsResponse")
}

func init() {
	proto.RegisterFile("nixprotocol/privacy/v1/query.proto", fileDescriptor_7fb4378f5df4cc1d)
}

var fileDescriptor_7fb4378f5df4cc1d = []byte{
	// 741 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4d, 0x53, 0xd3, 0x40,
	0x18, 0x66, 0xa1, 0x74, 0xe0, 0x15, 0x04, 0x57, 0xac, 0x9d, 0x58, 0x32, 0x35, 0x20, 0x16, 0x6a,
	0x13, 0xf9, 0xbc, 0x78, 0xc2, 0x8f, 0x03, 0xc3, 0xe8, 0x60, 0xf0, 0xe4, 0x25, 0x93, 0x36, 0x4b,
	0xc9, 0x50, 0xb2, 0x21, 0xd9, 0x74, 0x9a, 0x71, 0x3c, 0xe8, 0xcd, 0x9b, 0xa3, 0x37, 0xef, 0x5e,
	0x3d, 0xe8, 0x9f, 0xf0, 0xc8, 0x8c, 0x17, 0x8f, 0x0e, 0xe8, 0xff, 0x70, 0xb2, 0xd9, 0xd0, 0x52,
	0x9a, 0x52, 0x6e, 0xd9, 0xe7, 0xfd, 0x78, 0x9e, 0xdd, 0x7d, 0x9f, 0x0d, 0x28, 0x8e, 0xdd, 0x72,
	0x3d, 0xca, 0x68, 0x8d, 0x36, 0x34, 0xd7, 0xb3, 0x9b, 0x66, 0x2d, 0xd4, 0x9a, 0xcb, 0xda, 0x51,
	0x40, 0xbc, 0x50, 0xe5, 0x11, 0x9c, 0xeb, 0xc8, 0x51, 0x45, 0x8e, 0xda, 0x5c, 0x96, 0x0a, 0x75,
	0x4a, 0xeb, 0x0d, 0xa2, 0x99, 0xae, 0xad, 0x99, 0x8e, 0x43, 0x99, 0xc9, 0x6c, 0xea, 0xf8, 0x71,
	0x95, 0x94, 0xd6, 0x99, 0x85, 0x2e, 0x11, 0x39, 0x0a, 0x86, 0xe9, 0x97, 0x11, 0x91, 0x4e, 0x29,
	0xd3, 0xc9, 0x51, 0x40, 0x7c, 0xa6, 0xdc, 0x87, 0x1b, 0x1d, 0x98, 0xef, 0x52, 0xc7, 0x27, 0x18,
	0x43, 0xc6, 0xa3, 0x94, 0xe5, 0x51, 0x11, 0x95, 0x26, 0x74, 0xfe, 0xad, 0x3c, 0x82, 0x3b, 0x3c,
	0xf1, 0x45, 0xd0, 0x68, 0xd8, 0x7b, 0x36, 0xf1, 0x76, 0x99, 0xc9, 0x02, 0x5f, 0xf4, 0xc1, 0x05,
	0x18, 0x77, 0x92, 0x88, 0xa8, 0x6b, 0x03, 0xca, 0x1a, 0x14, 0x7a, 0x17, 0x0b, 0xc2, 0x19, 0x18,
	0xf5, 0x5d, 0xe2, 0xc4, 0x8c, 0x63, 0x7a, 0xbc, 0x50, 0x72, 0x30, 0xc3, 0xab, 0x5e, 0x79, 0x84,
	0x6c, 0x39, 0x7b, 0x34, 0xd1, 0xfc, 0x15, 0xc1, 0xad, 0xae, 0x80, 0xe8, 0x33, 0x0b, 0xe0, 0x90,
	0x16, 0x33, 0x6c, 0xc7, 0x22, 0x2d, 0xde, 0x2c, 0xa3, 0x8f, 0x47, 0xc8, 0x56, 0x04, 0x9c, 0xed,
	0x6b, 0xb8, 0xbd, 0xaf, 0x88, 0xda, 0x22, 0x2e, 0xdb, 0xcf, 0x8f, 0x14, 0x51, 0x69, 0x52, 0x8f,
	0x17, 0x78, 0x1e, 0xae, 0x9b, 0x35, 0x66, 0x37, 0x89, 0xc1, 0x3c, 0x42, 0x0c, 0xdb, 0xca, 0x67,
	0x78, 0xb3, 0x89, 0x18, 0xe5, 0xc4, 0x56, 0x44, 0xc7, 0xc3, 0x35, 0x1a, 0x38, 0x2c, 0x3f, 0x1a,
	0xd3, 0x45, 0xc8, 0x93, 0x08, 0x50, 0x66, 0x00, 0x73, 0x99, 0x3b, 0xa6, 0x67, 0x1e, 0x26, 0x27,
	0xa5, 0x3c, 0x87, 0x9b, 0xe7, 0x50, 0x21, 0x7d, 0x03, 0xb2, 0x2e, 0x47, 0xb8, 0xec, 0x6b, 0x2b,
	0xb2, 0xda, 0x7b, 0x0e, 0x54, 0x51, 0x27, 0xb2, 0x15, 0x59, 0x1c, 0xad, 0x4e, 0xea, 0xb6, 0xcf,
	0x3c, 0x3e, 0x14, 0x9d, 0x17, 0xbc, 0x0a, 0xb3, 0x29, 0xf1, 0x3e, 0x97, 0x9d, 0x87, 0x1c, 0x2f,
	0xda, 0x0c, 0x2c, 0x9b, 0x51, 0x6f, 0x9b, 0x84, 0x49, 0xbb, 0x4d, 0xb8, 0x7d, 0x21, 0x22, 0x1a,
	0x2d, 0xc0, 0x94, 0x19, 0xa3, 0x86, 0x1b, 0x54, 0x8d, 0x03, 0x12, 0x8a, 0x9e, 0x93, 0x02, 0xde,
	0x09, 0xaa, 0xdb, 0x24, 0x54, 0x66, 0xc5, 0x24, 0xed, 0x06, 0xae, 0x4b, 0x3d, 0x46, 0xac, 0xa7,
	0xc4, 0xa1, 0xed, 0xf3, 0xd9, 0x10, 0x1b, 0xba, 0x10, 0x16, 0x34, 0x39, 0xc8, 0x5a, 0x1c, 0xc9,
	0xa3, 0xe2, 0x48, 0x69, 0x5c, 0x17, 0xab, 0x95, 0x7f, 0x63, 0x30, 0xca, 0x0b, 0xf1, 0x3b, 0x04,
	0x99, 0x68, 0x8b, 0xb8, 0x94, 0x76, 0x86, 0xdd, 0x36, 0x90, 0x16, 0x07, 0xc8, 0x8c, 0xf9, 0x95,
	0xf9, 0xf7, 0xbf, 0xfe, 0x7e, 0x1e, 0x96, 0x71, 0x41, 0x4b, 0xb1, 0x1c, 0x1f, 0xab, 0x1f, 0x08,
	0xa6, 0xba, 0xa6, 0x1d, 0xaf, 0xf6, 0x25, 0xe9, 0x6d, 0x2c, 0x69, 0xed, 0x6a, 0x45, 0x42, 0xe4,
	0x3a, 0x17, 0xa9, 0xe1, 0x4a, 0x9a, 0xc8, 0x33, 0x6f, 0x6a, 0x6f, 0xce, 0x3e, 0xdf, 0xe2, 0x4f,
	0x08, 0xc6, 0x12, 0x53, 0xe1, 0x07, 0x7d, 0x99, 0xbb, 0x4c, 0x29, 0x55, 0x06, 0xcc, 0x16, 0x02,
	0x17, 0xb9, 0xc0, 0x39, 0x7c, 0x37, 0x4d, 0x60, 0xec, 0xbb, 0x48, 0xc7, 0x07, 0x04, 0xd9, 0x78,
	0xe8, 0xf1, 0x52, 0x5f, 0x92, 0x73, 0x3e, 0x93, 0xca, 0x03, 0xe5, 0x0a, 0x39, 0x0b, 0x5c, 0x4e,
	0x11, 0xcb, 0x69, 0x72, 0x62, 0xb7, 0xe1, 0xef, 0x08, 0xa6, 0xbb, 0x9d, 0x84, 0xfb, 0x5f, 0x51,
	0x8a, 0x31, 0xa5, 0xf5, 0x2b, 0x56, 0x09, 0xa5, 0xcb, 0x5c, 0x69, 0x19, 0x2f, 0xa6, 0x8e, 0x5f,
	0x47, 0xa5, 0xc1, 0x67, 0xf1, 0x0b, 0x02, 0x68, 0xfb, 0x15, 0xab, 0x7d, 0x89, 0x2f, 0x58, 0x5e,
	0xd2, 0x06, 0xce, 0x17, 0x12, 0xcb, 0x5c, 0xe2, 0x3d, 0x3c, 0x97, 0x26, 0x31, 0x79, 0x26, 0x0e,
	0x48, 0x88, 0xbf, 0x21, 0x98, 0xea, 0xb2, 0xfa, 0x25, 0x46, 0xe9, 0xfd, 0x6e, 0x5c, 0x62, 0x94,
	0x94, 0xd7, 0x44, 0x79, 0xc8, 0xb5, 0x2e, 0xe1, 0x52, 0x9a, 0x56, 0x3f, 0x29, 0x34, 0xe2, 0x77,
	0xe6, 0xf1, 0xb3, 0x9f, 0x27, 0x32, 0x3a, 0x3e, 0x91, 0xd1, 0x9f, 0x13, 0x19, 0x7d, 0x3c, 0x95,
	0x87, 0x8e, 0x4f, 0xe5, 0xa1, 0xdf, 0xa7, 0xf2, 0xd0, 0xeb, 0x72, 0xdd, 0x66, 0xfb, 0x41, 0x55,
	0xad, 0xd1, 0xc3, 0x73, 0xdd, 0x1c, 0xbb, 0x55, 0xa9, 0x51, 0xff, 0x90, 0xfa, 0x15, 0xdf, 0x3a,
	0x88, 0x7f, 0xc9, 0xd5, 0x2c, 0x0f, 0xaf, 0xfe, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x54, 0xc8, 0x09,
	0xf7, 0x13, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Root(ctx context.Context, in *QueryRootRequest, opts ...grpc.CallOption) (*QueryRootResponse, error)
	NullifierStatus(ctx context.Context, in *QueryNullifierStatusRequest, opts ...grpc.CallOption) (*QueryNullifierStatusResponse, error)
	TreeInfo(ctx context.Context, in *QueryTreeInfoRequest, opts ...grpc.CallOption) (*QueryTreeInfoResponse, error)
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	RegistrationRoot(ctx context.Context, in *QueryRegistrationRootRequest, opts ...grpc.CallOption) (*QueryRegistrationRootResponse, error)
	AuditorKey(ctx context.Context, in *QueryAuditorKeyRequest, opts ...grpc.CallOption) (*QueryAuditorKeyResponse, error)
	SupportedDenoms(ctx context.Context, in *QuerySupportedDenomsRequest, opts ...grpc.CallOption) (*QuerySupportedDenomsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Root(ctx context.Context, in *QueryRootRequest, opts ...grpc.CallOption) (*QueryRootResponse, error) {
	out := new(QueryRootResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.privacy.v1.Query/Root", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NullifierStatus(ctx context.Context, in *QueryNullifierStatusRequest, opts ...grpc.CallOption) (*QueryNullifierStatusResponse, error) {
	out := new(QueryNullifierStatusResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.privacy.v1.Query/NullifierStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TreeInfo(ctx context.Context, in *QueryTreeInfoRequest, opts ...grpc.CallOption) (*QueryTreeInfoResponse, error) {
	out := new(QueryTreeInfoResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.privacy.v1.Query/TreeInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.privacy.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegistrationRoot(ctx context.Context, in *QueryRegistrationRootRequest, opts ...grpc.CallOption) (*QueryRegistrationRootResponse, error) {
	out := new(QueryRegistrationRootResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.privacy.v1.Query/RegistrationRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AuditorKey(ctx context.Context, in *QueryAuditorKeyRequest, opts ...grpc.CallOption) (*QueryAuditorKeyResponse, error) {
	out := new(QueryAuditorKeyResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.privacy.v1.Query/AuditorKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SupportedDenoms(ctx context.Context, in *QuerySupportedDenomsRequest, opts ...grpc.CallOption) (*QuerySupportedDenomsResponse, error) {
	out := new(QuerySupportedDenomsResponse)
	err := c.cc.Invoke(ctx, "/nixprotocol.privacy.v1.Query/SupportedDenoms", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Root(context.Context, *QueryRootRequest) (*QueryRootResponse, error)
	NullifierStatus(context.Context, *QueryNullifierStatusRequest) (*QueryNullifierStatusResponse, error)
	TreeInfo(context.Context, *QueryTreeInfoRequest) (*QueryTreeInfoResponse, error)
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	RegistrationRoot(context.Context, *QueryRegistrationRootRequest) (*QueryRegistrationRootResponse, error)
	AuditorKey(context.Context, *QueryAuditorKeyRequest) (*QueryAuditorKeyResponse, error)
	SupportedDenoms(context.Context, *QuerySupportedDenomsRequest) (*QuerySupportedDenomsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Root(ctx context.Context, req *QueryRootRequest) (*QueryRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Root not implemented")
}
func (*UnimplementedQueryServer) NullifierStatus(ctx context.Context, req *QueryNullifierStatusRequest) (*QueryNullifierStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NullifierStatus not implemented")
}
func (*UnimplementedQueryServer) TreeInfo(ctx context.Context, req *QueryTreeInfoRequest) (*QueryTreeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TreeInfo not implemented")
}
func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) RegistrationRoot(ctx context.Context, req *QueryRegistrationRootRequest) (*QueryRegistrationRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistrationRoot not implemented")
}
func (*UnimplementedQueryServer) AuditorKey(ctx context.Context, req *QueryAuditorKeyRequest) (*QueryAuditorKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuditorKey not implemented")
}
func (*UnimplementedQueryServer) SupportedDenoms(ctx context.Context, req *QuerySupportedDenomsRequest) (*QuerySupportedDenomsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SupportedDenoms not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Root_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Root(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.privacy.v1.Query/Root",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Root(ctx, req.(*QueryRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NullifierStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNullifierStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NullifierStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.privacy.v1.Query/NullifierStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NullifierStatus(ctx, req.(*QueryNullifierStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TreeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTreeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TreeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.privacy.v1.Query/TreeInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TreeInfo(ctx, req.(*QueryTreeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.privacy.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegistrationRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRegistrationRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegistrationRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.privacy.v1.Query/RegistrationRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegistrationRoot(ctx, req.(*QueryRegistrationRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AuditorKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuditorKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AuditorKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.privacy.v1.Query/AuditorKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AuditorKey(ctx, req.(*QueryAuditorKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SupportedDenoms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySupportedDenomsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SupportedDenoms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nixprotocol.privacy.v1.Query/SupportedDenoms",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SupportedDenoms(ctx, req.(*QuerySupportedDenomsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nixprotocol.privacy.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Root",
			Handler:    _Query_Root_Handler,
		},
		{
			MethodName: "NullifierStatus",
			Handler:    _Query_NullifierStatus_Handler,
		},
		{
			MethodName: "TreeInfo",
			Handler:    _Query_TreeInfo_Handler,
		},
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "RegistrationRoot",
			Handler:    _Query_RegistrationRoot_Handler,
		},
		{
			MethodName: "AuditorKey",
			Handler:    _Query_AuditorKey_Handler,
		},
		{
			MethodName: "SupportedDenoms",
			Handler:    _Query_SupportedDenoms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nixprotocol/privacy/v1/query.proto",
}

func (m *QueryRootRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRootRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRootRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryRootResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRootResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRootResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryNullifierStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNullifierStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNullifierStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nullifier) > 0 {
		i -= len(m.Nullifier)
		copy(dAtA[i:], m.Nullifier)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Nullifier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryNullifierStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryNullifierStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryNullifierStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Spent {
		i--
		if m.Spent {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryTreeInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTreeInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTreeInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTreeInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTreeInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTreeInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TreeCount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TreeCount))
		i--
		dAtA[i] = 0x28
	}
	if m.ActiveTreeId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ActiveTreeId))
		i--
		dAtA[i] = 0x20
	}
	if m.Depth != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Depth))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0x12
	}
	if m.NextIndex != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.NextIndex))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRegistrationRootRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistrationRootRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistrationRootRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryRegistrationRootResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRegistrationRootResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRegistrationRootResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Root) > 0 {
		i -= len(m.Root)
		copy(dAtA[i:], m.Root)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Root)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAuditorKeyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuditorKeyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuditorKeyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAuditorKeyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuditorKeyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuditorKeyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AuditorPubKey) > 0 {
		i -= len(m.AuditorPubKey)
		copy(dAtA[i:], m.AuditorPubKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AuditorPubKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QuerySupportedDenomsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySupportedDenomsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySupportedDenomsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QuerySupportedDenomsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QuerySupportedDenomsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QuerySupportedDenomsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denoms) > 0 {
		for iNdEx := len(m.Denoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Denoms[iNdEx])
			copy(dAtA[i:], m.Denoms[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Denoms[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryRootRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryRootResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryNullifierStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Nullifier)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryNullifierStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Spent {
		n += 2
	}
	return n
}

func (m *QueryTreeInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTreeInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NextIndex != 0 {
		n += 1 + sovQuery(uint64(m.NextIndex))
	}
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Depth != 0 {
		n += 1 + sovQuery(uint64(m.Depth))
	}
	if m.ActiveTreeId != 0 {
		n += 1 + sovQuery(uint64(m.ActiveTreeId))
	}
	if m.TreeCount != 0 {
		n += 1 + sovQuery(uint64(m.TreeCount))
	}
	return n
}

func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRegistrationRootRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryRegistrationRootResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Root)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAuditorKeyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAuditorKeyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AuditorPubKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QuerySupportedDenomsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QuerySupportedDenomsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Denoms) > 0 {
		for _, s := range m.Denoms {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryRootRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRootRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRootRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRootResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRootResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRootResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNullifierStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNullifierStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNullifierStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nullifier", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nullifier = append(m.Nullifier[:0], dAtA[iNdEx:postIndex]...)
			if m.Nullifier == nil {
				m.Nullifier = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryNullifierStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryNullifierStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryNullifierStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spent", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Spent = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTreeInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTreeInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTreeInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTreeInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTreeInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTreeInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextIndex", wireType)
			}
			m.NextIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depth", wireType)
			}
			m.Depth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Depth |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveTreeId", wireType)
			}
			m.ActiveTreeId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveTreeId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreeCount", wireType)
			}
			m.TreeCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TreeCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistrationRootRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistrationRootRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistrationRootRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRegistrationRootResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRegistrationRootResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRegistrationRootResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Root", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Root = append(m.Root[:0], dAtA[iNdEx:postIndex]...)
			if m.Root == nil {
				m.Root = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuditorKeyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuditorKeyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuditorKeyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuditorKeyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuditorKeyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuditorKeyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditorPubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditorPubKey = append(m.AuditorPubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.AuditorPubKey == nil {
				m.AuditorPubKey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySupportedDenomsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySupportedDenomsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySupportedDenomsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QuerySupportedDenomsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QuerySupportedDenomsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QuerySupportedDenomsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denoms = append(m.Denoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
