// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nixprotocol/privacy/v1/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the nixpool privacy module.
type Params struct {
	TreeDepth       uint32   `protobuf:"varint,1,opt,name=tree_depth,json=treeDepth,proto3" json:"tree_depth,omitempty"`
	RegTreeDepth    uint32   `protobuf:"varint,2,opt,name=reg_tree_depth,json=regTreeDepth,proto3" json:"reg_tree_depth,omitempty"`
	AuditorPubKey   []byte   `protobuf:"bytes,3,opt,name=auditor_pub_key,json=auditorPubKey,proto3" json:"auditor_pub_key,omitempty"`
	SupportedDenoms []string `protobuf:"bytes,4,rep,name=supported_denoms,json=supportedDenoms,proto3" json:"supported_denoms,omitempty"`
	ChainBinding    []byte   `protobuf:"bytes,5,opt,name=chain_binding,json=chainBinding,proto3" json:"chain_binding,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a52e879bf30640e, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetTreeDepth() uint32 {
	if m != nil {
		return m.TreeDepth
	}
	return 0
}

func (m *Params) GetRegTreeDepth() uint32 {
	if m != nil {
		return m.RegTreeDepth
	}
	return 0
}

func (m *Params) GetAuditorPubKey() []byte {
	if m != nil {
		return m.AuditorPubKey
	}
	return nil
}

func (m *Params) GetSupportedDenoms() []string {
	if m != nil {
		return m.SupportedDenoms
	}
	return nil
}

func (m *Params) GetChainBinding() []byte {
	if m != nil {
		return m.ChainBinding
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "nixprotocol.privacy.v1.Params")
}

func init() {
	proto.RegisterFile("nixprotocol/privacy/v1/types.proto", fileDescriptor_6a52e879bf30640e)
}

var fileDescriptor_6a52e879bf30640e = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0xc1, 0x4a, 0xc3, 0x30,
	0x1c, 0xc7, 0xf1, 0xc5, 0xe9, 0x60, 0xa1, 0x75, 0xd2, 0x83, 0xf4, 0x62, 0x28, 0x53, 0xa4, 0x22,
	0x6b, 0x19, 0xbe, 0xc1, 0x98, 0x27, 0x2f, 0xa3, 0x78, 0xf2, 0x12, 0xda, 0x26, 0xb4, 0x61, 0x36,
	0x09, 0x49, 0x5a, 0xd6, 0xb7, 0xf0, 0xa5, 0x04, 0x8f, 0x3b, 0x7a, 0x94, 0xf6, 0x45, 0x64, 0xd9,
	0x18, 0xbd, 0x7e, 0xfe, 0x5f, 0xfe, 0x87, 0x1f, 0x9c, 0x73, 0xb6, 0x93, 0x4a, 0x18, 0x91, 0x8b,
	0xcf, 0x58, 0x2a, 0xd6, 0xa4, 0x79, 0x1b, 0x37, 0xcb, 0xd8, 0xb4, 0x92, 0xea, 0xc8, 0x5e, 0xbc,
	0xdb, 0x41, 0x13, 0x9d, 0x9a, 0xa8, 0x59, 0xce, 0xbf, 0x01, 0x9c, 0x6c, 0x52, 0x95, 0x56, 0xda,
	0xbb, 0x83, 0xd0, 0x28, 0x4a, 0x31, 0xa1, 0xd2, 0x94, 0x3e, 0x08, 0x40, 0xe8, 0x26, 0xd3, 0x83,
	0xac, 0x0f, 0xe0, 0x3d, 0xc0, 0x6b, 0x45, 0x0b, 0x3c, 0x48, 0x2e, 0x6c, 0xe2, 0x28, 0x5a, 0xbc,
	0x9f, 0xab, 0x47, 0x38, 0x4b, 0x6b, 0xc2, 0x8c, 0x50, 0x58, 0xd6, 0x19, 0xde, 0xd2, 0xd6, 0x1f,
	0x07, 0x20, 0x74, 0x12, 0xf7, 0xc4, 0x9b, 0x3a, 0x7b, 0xa3, 0xad, 0xf7, 0x04, 0x6f, 0x74, 0x2d,
	0xa5, 0x50, 0x86, 0x12, 0x4c, 0x28, 0x17, 0x95, 0xf6, 0x2f, 0x83, 0x71, 0x38, 0x4d, 0x66, 0x67,
	0x5f, 0x5b, 0xf6, 0xee, 0xa1, 0x9b, 0x97, 0x29, 0xe3, 0x38, 0x63, 0x9c, 0x30, 0x5e, 0xf8, 0x57,
	0xf6, 0xa1, 0x63, 0x71, 0x75, 0xb4, 0xd5, 0xeb, 0x4f, 0x87, 0xc0, 0xbe, 0x43, 0xe0, 0xaf, 0x43,
	0xe0, 0xab, 0x47, 0xa3, 0x7d, 0x8f, 0x46, 0xbf, 0x3d, 0x1a, 0x7d, 0x3c, 0x17, 0xcc, 0x94, 0x75,
	0x16, 0xe5, 0xa2, 0x8a, 0x87, 0x43, 0x71, 0xb6, 0x5b, 0xe4, 0x42, 0x57, 0x42, 0x2f, 0x34, 0xd9,
	0x1e, 0xc7, 0xca, 0x26, 0xf6, 0xfc, 0xf2, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xaa, 0xf7, 0xa0,
	0x53, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainBinding) > 0 {
		i -= len(m.ChainBinding)
		copy(dAtA[i:], m.ChainBinding)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ChainBinding)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.SupportedDenoms) > 0 {
		for iNdEx := len(m.SupportedDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SupportedDenoms[iNdEx])
			copy(dAtA[i:], m.SupportedDenoms[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.SupportedDenoms[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.AuditorPubKey) > 0 {
		i -= len(m.AuditorPubKey)
		copy(dAtA[i:], m.AuditorPubKey)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.AuditorPubKey)))
		i--
		dAtA[i] = 0x1a
	}
	if m.RegTreeDepth != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RegTreeDepth))
		i--
		dAtA[i] = 0x10
	}
	if m.TreeDepth != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TreeDepth))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TreeDepth != 0 {
		n += 1 + sovTypes(uint64(m.TreeDepth))
	}
	if m.RegTreeDepth != 0 {
		n += 1 + sovTypes(uint64(m.RegTreeDepth))
	}
	l = len(m.AuditorPubKey)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.SupportedDenoms) > 0 {
		for _, s := range m.SupportedDenoms {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = len(m.ChainBinding)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreeDepth", wireType)
			}
			m.TreeDepth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TreeDepth |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegTreeDepth", wireType)
			}
			m.RegTreeDepth = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegTreeDepth |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuditorPubKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuditorPubKey = append(m.AuditorPubKey[:0], dAtA[iNdEx:postIndex]...)
			if m.AuditorPubKey == nil {
				m.AuditorPubKey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SupportedDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SupportedDenoms = append(m.SupportedDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainBinding", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainBinding = append(m.ChainBinding[:0], dAtA[iNdEx:postIndex]...)
			if m.ChainBinding == nil {
				m.ChainBinding = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
